config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get '/static_pages/home', to: 'static_pages#home', as: '/home'
  get '/contact', to: 'static_pages#contact', as: '/contact'
  get '/team', to: 'static_pages#team', as: '/team'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  resources :gossips do
    resources :commentaries, only:[:index,:show,:new,:create]
  end

  resources :users
  resources :cities
  resources :sessions, only:[:new,:create,:destroy]
  get '/sessions/profile', to: 'sessions#profile'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/commentary.rb
class Commentary < ApplicationRecord
  belongs_to :user, optional: :true
  belongs_to :gossip, optional: :true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :join_tag_gossips
  has_many :tags, through: :join_tag_gossips
  has_many :commentaries
end

app/models/join_tag_gossip.rb
class JoinTagGossip < ApplicationRecord
  belongs_to :tag
  belongs_to :gossip
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :join_tag_gossips
  has_many :gossips, through: :join_tag_gossips
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  belongs_to :city, optional: true
  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id',class_name:"PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id',class_name:"PrivateMessage"
  has_many :commentaries
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    @cities = City.all
  end

  def show
    @city = City.find(params[:id])
    @user = User.find_by city_id: @city.id
    @gossips = Gossip.where user_id: @user.id
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :authenticate_user, only: [:index,:create,:new,:edit,:destroy]
  def index
     @gossips = Gossip.all
  end
  
  def show
    @gossip = Gossip.find(params[:id])
    find_user = @gossip.user_id
    @user = User.find(find_user)
    @commentaries = Commentary.where gossip_id: @gossip.id
  end
  def edit
    @gossip = Gossip.find(params[:id])
    unless current_user.id == @gossip.user_id
      redirect_to gossip_path
    end
  end  

  def update
    @gossip = Gossip.find(params[:id])
    if current_user.id == @gossip.user_id
      @gossip.update!(gossip_params)
    end
  end
  def new
    @gossip = Gossip.new
  end

  def create
    gossip = Gossip.new(gossip_params)
    gossip.user = current_user
    gossip.save
    redirect_to gossip_path(gossip.id)
  end

  def destroy

    @gossip = Gossip.find(params[:id])
    if current_user.id == @gossip.user_id
      @gossip.destroy
      redirect_to gossip_path
    end
  end

  private
  def gossip_params
    params.require(:gossip).permit(:title,:content)
  end

  def authenticate_user
    unless current_user
      flash[:danger] = "Please log in."
      redirect_to new_session_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def create 
    puts "%" *60
    puts params
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to "/sessions/profile"
    else
      render 'new'
    end
  end
  def destroy
    session.delete(:user_id) 
    redirect_to "/sessions/new"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all 
  end

  def show
    @user = User.find(params[:id])
    @city = City.find_by(id: @user.city_id)
  end

  def new
    @user = User.new
    @city = City.all
  end

  def create
    @user = User.new(user_params)
    @user.save!
    redirect_to "/sessions/new"
  end

  def edit
  end

  def update
  end

  def destroy
  end
  
  private
  def user_params
    params.require(:user).permit(:first_name,:last_name,:password,:email,:description,:age,:city_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/commentaries_helper.rb
module CommentariesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by(id: session[:user_id])
  end

  def log_in(user)
    session[:user_id] = user.id
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cities/create.html.erb
<h1>Cities#create</h1>
<p>Find me in app/views/cities/create.html.erb</p>

app/views/cities/destroy.html.erb
<h1>Cities#destroy</h1>
<p>Find me in app/views/cities/destroy.html.erb</p>

app/views/cities/edit.html.erb
<h1>Cities#edit</h1>
<p>Find me in app/views/cities/edit.html.erb</p>

app/views/cities/index.html.erb
<h1 class="ps-5 my-3">Liste de tous les villes</h1>
<%@cities.each do |city|%>
<div class="py-2 ps-5" style="outline:darkgrey 1px solid; background-color: aliceblue;">
<h3>
<%=city.name%>
</h3>
<h5>
<%=city.zip_code%>
</h5>
<a href="<%=city_path(city.id)%>" class="btn btn-primary btn-sm my-4">Voir la ville</a>
</div>
<%end%>

app/views/cities/new.html.erb
<h1>Cities#new</h1>
<p>Find me in app/views/cities/new.html.erb</p>

app/views/cities/show.html.erb
<div class="container my-5 d-flex justify-content-center align-items-center">
  <table>
    <thead>
      <tr>
        <th colspan="2"><h3><%=@city.name%></h3></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Zipcode : "<%=@city.zip_code%>"</td>
      </tr>
      <%@gossips.each do |gossip|%>
      <tr>
        <td>
          Gossip : <%=gossip.title%>
          <a
            class="my-5 btn btn-sm btn-outline-secondary"
            href="<%=gossip_path(gossip.id)%>"
            >Voir le gossip</a
          >
        </td>
      </tr>
      <%end%>
    </tbody>
  </table>
</div>

app/views/cities/update.html.erb
<h1>Cities#update</h1>
<p>Find me in app/views/cities/update.html.erb</p>

app/views/gossips/edit.html.erb
<div class="container my-5 py-5 d-flex flex-column justify-content-center align-items-center">
<h1>Editer le gossip</h1>
<%= form_for @gossip do |f| %>
  <div class="form-group py-2">
    <label>Titre du gossip</label>
    <%=f.text_field :title%>
  </div>

  <div class="form-group py-2">
    <label>Contenu du gossip<label>
    <%=f.text_field :content%>
  </div>

  <div class="form-group py-2">
    <button type="submit" class="btn btn-sm btn-primary">Modifier</button>
    <a href="<%= gossips_path%>" class="btn btn-sm btn-outline-primary">Revenir aux gossips</a>
  </div>
<%end%>
</div>

app/views/gossips/index.html.erb
<div class="container mt-5 d-flex justify-content-center flex-column align-items-center">
  <h1 class="mb-5">Tous les gossips : </h1>
  <%= button_to "Ajouter gossip", new_gossip_path, method: :get, class: 'btn btn-sm btn-outline-success'%>
    <%@gossips.each do |gossip|%>
      <h2 class="my-3">
        <%=gossip.title%>
      </h2>
      <p>
        <%= gossip.content%>
      </p>
      <div class="container col-4 d-flex justify-content-around my-4">
        <a href="<%=gossip_path(gossip.id)%>" class="btn btn-sm btn-primary">Voir</a>
        <a href="<%=edit_gossip_path(gossip.id)%>" class="btn btn-sm btn btn-outline-primary">Editer</a>
        <%= button_to "Supprimer", gossip_path(gossip.id), method: :delete, class: 'btn btn-sm btn-outline-danger'%>
      </div>
    <%end%>

app/views/gossips/new.html.erb
<div class="container my-5 py-5 d-flex flex-column justify-content-center align-items-center">
<h1>Créer un gossip</h1>
<%= form_for @gossip do |f| %>
  <div class="form-group py-2">
    <label>Titre du gossip</label>
    <%=f.text_field :title%>
  </div>

  <div class="form-group py-2">
    <label>Contenu du gossip<label>
    <%=f.text_field :content%>
  </div>

  <div class="form-group py-2">
  <a href="<%= gossips_path%>" class="btn btn-sm btn-outline-primary">Revenir aux gossips</a>
    <button type="submit" class="btn btn-sm btn-primary">Ajouter le gossip</button>
  </div>
<%end%>
</div>

app/views/gossips/show.html.erb
<div class="container mt-5 d-flex justify-content-center flex-column align-items-center ">
  <h1><%=@gossip.title%></h1>
  <h2><%=@gossip.content%></h2>
    <a href="<%= gossips_path%>" class="btn btn-sm btn-primary my-2">Revenir aux gossips</a>
    <a href="<%= user_path(@user.id)%>" class="btn btn-sm btn-outline-primary my-2">Voir le profil de <%=@user.first_name%></a>
    <a href="<%=edit_gossip_path%>"class="btn btn-sm">Modifier</a>
    <%= button_to "Ajouter un commentaire", new_gossip_commentary_path(@gossip.id), method: :get, class:" my-3 btn btn-sm btn-outline-secondary"%>
    <div class="container col-5">
    <h5 class="my-4 ms-2">Commentaires : </h5>
      <%@commentaries.each do |commentary|%>
        <div class="container ms-0">
          <p><%=User.find(commentary.user_id).first_name%> : 
          <%=commentary.content%></p>
        </div>
      <%end%>
    </div>
  </div>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<div class="container my-5 d-flex justify-content-center align-items-center">
<h1>Page indisponible pour le moment</h1>
</div>

app/views/users/index.html.erb
<h1 class="ps-5 my-3">Liste de tous les utilisateurs</h1>
<%@users.each do |user|%>
<div class="py-2 ps-5" style="outline:darkgrey 1px solid; background-color: aliceblue;">
<h3>
<%=user.first_name%>
</h3>
<h5>
<%=user.last_name%>
</h5>
<a href="<%=user_path(user.id)%>" class="btn btn-primary btn-sm my-4">Voir le profil</a>
</div>
<%end%>

app/views/users/new.html.erb
  <div class="container my-5 d-flex flex-column justify-content-center align-items-center">
    <h1 class="my-3">Créer un compte</h1>
<%= form_with model:@user do |form| %>
  <div class="container my-5 d-flex flex-column justify-content-center align-items-center">

  <%= form.label :first_name, "Prénom:", class:"my-2" %>
  <%= form.text_field :first_name %>

  <%= form.label :last_name, "Nom :", class:"my-2" %>

  <%= form.text_field :last_name %>

  <%= form.label :description, "Description :", class:"my-2" %>
  <%= form.text_field :description %>

  <%= form.label :age, "Age :", class:"my-2" %>
  <%= form.text_field :age %>

  <%= form.label :age, "Ville :", class:"my-2" %>
  <%= form.select :city_id, @city.map{|c| c.id }%>

  <%= form.label :email, "E-mail", class:"my-2" %>
  <%= form.text_field :email %>

  <%= form.label :password, "Mot de passe :" , class:"my-2"%>
  <%= form.password_field :password %>
  
  <%= form.submit "Créer un compte", class:"my-4 btn btn-success" %>
</div>
<% end %>
</div>
</div>

app/views/users/show.html.erb
<div class="container my-5 d-flex justify-content-center align-items-center">
<table>
  <thead>
    <tr>
      <th colspan="2"><%=@user.first_name%> <%=@user.last_name%></th>
    </tr>
    </thead>
    <tbody>
      <tr>
        <td>Description : "<%=@user.description%>"</td>
      </tr>
      <tr>
        <td>Email : <%=@user.email%></td>
      </tr>
      <tr>
        <td>Age : <%=@user.age%></td>
      </tr>
      <tr>
        <td>Ville : <%=@city.name%> <a href="<%=city_path(@city.id)%>">Voir la ville</a> </td>
      </tr>
    </tbody>
</table>
</div>

app/views/users/update.html.erb
<div class="container my-5 d-flex justify-content-center align-items-center">
<h1>Page indisponible pour le moment</h1>
</div>