config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get '/static_pages/home', to: 'static_pages#home', as: '/home'
  get '/contact', to: 'static_pages#contact', as: '/contact'
  get '/team', to: 'static_pages#team', as: '/team'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  resources :gossips do
    resources :commentaries, only:[:index,:show,:new,:create]
  end

  resources :users
  resources :cities
  resources :sessions, only:[:new,:create,:destroy]
  get '/sessions/profile', to: 'sessions#profile'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/commentary.rb
class Commentary < ApplicationRecord
  belongs_to :user, optional: :true
  belongs_to :gossip, optional: :true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :join_tag_gossips
  has_many :tags, through: :join_tag_gossips
  has_many :commentaries
end

app/models/join_tag_gossip.rb
class JoinTagGossip < ApplicationRecord
  belongs_to :tag
  belongs_to :gossip
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :join_tag_gossips
  has_many :gossips, through: :join_tag_gossips
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  belongs_to :city, optional: true
  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id',class_name:"PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id',class_name:"PrivateMessage"
  has_many :commentaries
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    @cities = City.all
  end

  def show
    @city = City.find(params[:id])
    @user = User.find_by city_id: @city.id
    @gossips = Gossip.where user_id: @user.id
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all 
  end

  def show
    @user = User.find(params[:id])
    @city = City.find_by(id: @user.city_id)
  end

  def new
    @user = User.new
    @city = City.all
  end

  def create
    @user = User.new(user_params)
    @user.save!
    redirect_to "/sessions/new"
  end

  def edit
  end

  def update
  end

  def destroy
  end
  
  private
  def user_params
    params.require(:user).permit(:first_name,:last_name,:password,:email,:description,:age,:city_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/commentaries_helper.rb
module CommentariesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by(id: session[:user_id])
  end

  def log_in(user)
    session[:user_id] = user.id
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThpGossip</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg ms-5">
    <a class="navbar-brand" href="<%=root_path%>">The Gossip Project</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-between" id="navbarNav">
      <ul class="navbar-nav">
        <div class="container d-flex">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%=root_path%>">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%=team_path%>">Team</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%=contact_path%>">Contact</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%=gossips_path%>">Gossips</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%=users_path%>">Utilisateurs</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%=cities_path%>">Villes</a>
        </li>
        </div>
        <div class="container d-flex align-items-center">
        <li class="nav-item ">
        <%= button_to "Se connecter", new_session_path, method: :get, class:"btn btn-sm btn-primary mx-2"%>
        </li>
        <li class="nav-item ">
        <%= button_to "Créer un compte", new_user_path, method: :get, class:"btn btn-sm btn-outline-primary mx-2"%>
        </li>
        <li class="nav-item ">
        <%= button_to "Se déconnecter", session_path(session.id), method: :delete, class:"btn btn-sm btn-outline-danger mx-2"%>
        </li>
      </div>
      </ul>
    </div>
  </div>
</nav>






    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <%= yield %>
  </body>
</html>